/* ──────────────────────────────────────────────────────────────────────────
 * sim/faq.js — Extended knowledge bank for the NDT15 Copilot
 *
 * A large curated FAQ covering digital-twin concepts, the 15 layers, port
 * operations, commercial/customer topics, technology, ESG/energy, safety,
 * resilience, automation and strategy. Each entry resolves dozens of phrasings
 * (diacritic-insensitive + synonym folding in knowledge.js), so together with
 * the dynamic locator (blocks/ships/trucks/landmarks) the bot answers thousands
 * of distinct questions. Append freely — no code changes needed.
 *
 * Entry shape: { cat, kw (keywords, any casing/diacritics), a (answer),
 *                act? (optional action: {feature}|{fly}|{descend}|{future}) }
 * ────────────────────────────────────────────────────────────────────────── */
export const FAQ = [
  /* ── DIGITAL TWIN — khái niệm ─────────────────────────────────────────── */
  { cat: 'Digital Twin', kw: 'loi ich digital twin tac dung gia tri vi sao quan trong', a: 'Lợi ích digital twin: ra quyết định dựa trên dữ liệu thay vì phỏng đoán, giảm 20–30% chi phí vận hành, tăng 15–23% hiệu suất, giảm thời gian dừng máy, mô phỏng "what-if" trước khi làm thật, và tối ưu năng lượng 10–25%. Với cảng: bớt tắc nghẽn, bớt phí neo/lưu, vận hành an toàn & xanh hơn.' },
  { cat: 'Digital Twin', kw: 'roi hoan von chi phi dau tu bao lau co lai payback', a: 'ROI digital twin thường rất tốt: nhiều dự án báo cáo giảm 20–30% chi phí vận hành và thời gian hoàn vốn dưới ~18 tháng. Giá trị đến từ tối ưu khai thác, giảm sự cố, tiết kiệm năng lượng và tránh các quyết định sai tốn kém.' },
  { cat: 'Digital Twin', kw: 'khac nhau mo phong simulation digital twin so sanh', a: 'Khác biệt: mô phỏng (simulation) chạy kịch bản trên mô hình TĨNH, offline; digital twin là bản sao SỐNG được CẬP NHẬT REAL-TIME từ dữ liệu cảm biến của tài sản thật, vừa phản chiếu hiện tại vừa mô phỏng tương lai. NDT15 còn thêm tua thời gian (CHRONOS).' },
  { cat: 'Digital Twin', kw: 'khac metaverse vs metaverse khac gi', a: 'Metaverse hướng tới không gian ảo cho con người tương tác/giải trí; digital twin là bản sao trung thực của tài sản VẬT LÝ phục vụ vận hành & ra quyết định. NDT15 là digital twin (có thể trình bày trải nghiệm 3D giống metaverse nhưng mục tiêu là điều hành cảng).' },
  { cat: 'Digital Twin', kw: 'khac mo hinh 3d binh thuong model tinh', a: 'Mô hình 3D thường chỉ là hình ảnh tĩnh. Digital twin gắn dữ liệu sống (IoT, AIS, TOS), có hành vi/logic và cập nhật theo thời gian thực — bạn click vật thể là thấy trạng thái thật, không chỉ hình dáng.' },
  { cat: 'Digital Twin', kw: 'nguon du lieu lay tu dau cam bien data sources feed', a: 'Dữ liệu của twin đến từ: AIS (vị trí tàu), TOS/cảng (lịch tàu, bãi), cảm biến IoT (CO₂/nước/nhiệt/áp suất), camera ALPR & nhiệt, radar, GPS thiết bị, hệ thống điện/năng lượng, và GIS/BIM. Tất cả hợp nhất ở trung tâm dữ liệu (lớp 13).' },
  { cat: 'Digital Twin', kw: 'thoi gian thuc real-time cap nhat bao lau tan suat', a: 'Twin cập nhật gần thời gian thực: AIS ~30 giây/lần, cảm biến môi trường ~1 phút/lần, vị trí thiết bị/xe liên tục. Trạng thái hiển thị trong cảnh 3D phản ánh đúng thời điểm hiện tại (CHRONOS hiển thị giờ thực).' },
  { cat: 'Digital Twin', kw: 'do chinh xac accuracy tin cay co dung khong', a: 'Độ chính xác phụ thuộc chất lượng dữ liệu & mô hình; với hạ tầng IoT tốt, vị trí và trạng thái phản ánh sát thực tế. Phần mô phỏng what-if cho kết quả ĐỊNH HƯỚNG (xu hướng/độ lớn) để hỗ trợ quyết định, không phải dự báo tuyệt đối.' },
  { cat: 'Digital Twin', kw: 'bao mat security an toan du lieu rui ro hack', a: 'An toàn dữ liệu twin: phân quyền truy cập, mã hóa, giám sát an ninh mạng (xem kịch bản tấn công cổng), đặt hạ tầng máy chủ ở trung tâm dữ liệu ngầm cách ly. Dữ liệu vận hành nhạy cảm được kiểm soát chặt.' },
  { cat: 'Digital Twin', kw: 'digital twin cap do may cap trinh do muc do bao nhieu cap level descriptive diagnostic predictive prescriptive autonomous', a: 'Digital twin có 6 cấp: 0 Standalone (offline), 1 Descriptive (phản chiếu), 2 Diagnostic (chẩn đoán), 3 Predictive (dự báo), 4 Prescriptive (đề xuất hành động), 5 Autonomous (tự ra quyết định). NDT15 hướng tới cấp 4 nhờ CHRONOS (what-if + hóa giải).' },
  { cat: 'Digital Twin', kw: 'ai role vai tro tri tue nhan tao trong twin', a: 'AI trong twin: tối ưu xếp bãi & cập bến (JIT), nhận diện biển số (ALPR) và mục tiêu an ninh, dự báo nhu cầu/giá điện, phát hiện bất thường, và mô phỏng kịch bản. AI biến dữ liệu thô thành cảnh báo & lệnh điều hành.' },
  { cat: 'Digital Twin', kw: 'iot internet van vat cam bien lam gi', a: 'IoT là mạng cảm biến gắn trên thiết bị/hạ tầng (cẩu, cổng, phao, ống ngầm, trạm điện) đo đạc liên tục và gửi dữ liệu về twin — là "giác quan" của bản sao số.' },
  { cat: 'Digital Twin', kw: 'bao tri du doan predictive maintenance bao tri', a: 'Bảo trì dự đoán: twin theo dõi rung động/nhiệt độ/giờ chạy của cẩu, bơm, biến áp để dự báo hỏng hóc TRƯỚC khi xảy ra → bảo trì đúng lúc, giảm dừng máy đột xuất.' },
  { cat: 'Digital Twin', kw: 'what if kich ban gia dinh mo phong tinh huong', a: 'Khả năng "what-if": tiêm một giả định (cẩu hỏng, bão, mất điện) và xem hậu quả lan truyền trước khi nó xảy ra thật. Bấm "⚡ Fork Reality" để chạy, hoặc hỏi tôi "nếu … thì sao?".', act: { picker: true } },
  { cat: 'Digital Twin', kw: 'vong doi lifecycle thiet ke van hanh xay dung', a: 'Digital twin đồng hành cả vòng đời tài sản: thiết kế (mô phỏng trước khi xây), xây dựng (BIM), vận hành (giám sát real-time), bảo trì (dự đoán) và nâng cấp/mở rộng.' },
  { cat: 'Digital Twin', kw: 'ai tao ra khai niem lich su nguon goc digital twin', a: 'Khái niệm "digital twin" được Michael Grieves nêu (2002) và NASA phát triển sớm cho hàng không vũ trụ. Ngày nay phổ biến ở sản xuất, năng lượng, hạ tầng và cảng biển.' },
  { cat: 'Digital Twin', kw: 'cloud edge dien toan dam may bien', a: 'Twin thường kết hợp ĐÁM MÂY (tổng hợp, mô phỏng nặng, lưu trữ) và EDGE (xử lý tại chỗ độ trễ thấp cho điều khiển thiết bị). NDT15 đặt trung tâm dữ liệu ngầm làm lõi.' },

  /* ── 15 LỚP (NDT 15) ──────────────────────────────────────────────────── */
  { cat: '15 Lớp', kw: '15 lop la nhung gi liet ke danh sach cac lop layer', a: '15 lớp của NDT15 là các tầng dữ liệu/hệ thống phối hợp: AIS (định vị tàu), TIS (thông tin bến), GIS (bản đồ không gian), BIM (mô hình công trình), MMIS (vật tư/thiết bị), CIM (quản lý cảng), EIS (môi trường), SSIS (an ninh giám sát), năng lượng, giao thông/cổng, logistics, tài chính, hạ tầng ngầm (lớp 13), v.v. — hợp nhất tại trung tâm dữ liệu.' },
  { cat: '15 Lớp', kw: 'tis thong tin ben terminal information system la gi', a: 'TIS (Terminal Information System): lớp thông tin khai thác bến — trạng thái cầu bến, tiến độ bốc dỡ, sức chứa, lịch tàu — đầu vào cho điều phối JIT và xếp bãi.' },
  { cat: '15 Lớp', kw: 'cim quan ly cang city information management la gi', a: 'CIM (City/Cảng Information Management): lớp quản lý tổng thể cảng/đô thị cảng, kết nối hạ tầng, giao thông và dịch vụ.' },
  { cat: '15 Lớp', kw: 'mmis vat tu thiet bi material la gi', a: 'MMIS: lớp quản lý vật tư & thiết bị (cẩu, xe, phụ tùng) — theo dõi tình trạng, bảo trì, sẵn sàng khai thác.' },
  { cat: '15 Lớp', kw: 'ssis an ninh giam sat security surveillance la gi', a: 'SSIS: lớp an ninh & giám sát — radar, camera, drone, kiểm soát ra vào — tạo vành đai an ninh 360°.' },
  { cat: '15 Lớp', kw: 'eis moi truong environment information system la gi', a: 'EIS (Environment Information System): lớp môi trường — cảm biến CO₂/SOx/NOx, chất lượng nước, tiếng ồn — tổng hợp dashboard ESG.' },
  { cat: '15 Lớp', kw: 'tai sao 15 con so y nghia vi sao 15 lop', a: 'Con số 15 tượng trưng cho bộ 15 lớp dữ liệu cần thiết để số hóa TOÀN DIỆN một cảng — từ mặt nước, bến, bãi, cổng, an ninh, môi trường, năng lượng đến hạ tầng ngầm — thay vì chỉ vài hệ thống rời rạc.' },

  /* ── VẬN HÀNH CẢNG ─────────────────────────────────────────────────────── */
  { cat: 'Vận hành', kw: 'quy trinh cap ben berthing buoc tau vao cang the nao', a: 'Quy trình cập bến: tàu báo ETA qua AIS → hoa tiêu & tàu lai dắt hỗ trợ vào luồng → cập đúng cầu bến đã phân (điều phối JIT để không neo chờ) → cẩu STS bốc/dỡ → hoàn tất, rời bến. Twin theo dõi toàn bộ real-time.' },
  { cat: 'Vận hành', kw: 'dwell time thoi gian luu bai container nam bao lau', a: 'Dwell time (thời gian lưu bãi) là số ngày container nằm tại bãi trước khi rời cảng (trung bình ~2–5 ngày trong mô hình). Dwell cao gây quá tải bãi; AI xếp bãi & JIT giúp giảm dwell.' },
  { cat: 'Vận hành', kw: 'free time thoi gian mien phi luu container nhap mien cuoc luu', a: 'Free time là số ngày miễn phí lưu container nhập tại bãi; quá hạn sẽ phát sinh phí lưu (demurrage). Khách nên lấy hàng trong free time để tránh phí. (Số ngày cụ thể theo biểu của hãng tàu/cảng.)' },
  { cat: 'Vận hành', kw: 'demurrage detention phi luu container phi luu xe', a: 'Demurrage = phí lưu container trong cảng quá free time; Detention = phí giữ container (vỏ) ngoài cảng quá hạn trả. Đây là chi phí logistics quan trọng cần tối ưu.' },
  { cat: 'Vận hành', kw: 'throughput san luong nang suat cang bao nhieu teu', a: 'Throughput (sản lượng) đo bằng TEU thông qua trong kỳ; là chỉ số năng lực cảng. Tăng throughput nhờ giảm thời gian tác nghiệp tàu/cẩu/cổng — đúng những gì twin tối ưu.' },
  { cat: 'Vận hành', kw: 'gate turn time thoi gian xe qua cong nhanh khong', a: 'Gate turn time = thời gian một xe tải hoàn tất ra/vào cổng. Cổng tự động ALPR + booking slot đưa thông quan xuống ~2 phút (giảm ~90%), hết cảnh kẹt xe đầu kéo.', act: { feature: 'CỔNG' } },
  { cat: 'Vận hành', kw: 'un tac tac nghen congestion ket xe ket bai xu ly', a: 'Tắc nghẽn được xử lý bằng: điều phối JIT (tàu đến đúng lúc), booking slot xe tải, AI xếp bãi tránh đảo chuyển, và mô phỏng what-if để xử lý sự cố trước. Twin còn cảnh báo khu bãi >90% tải.' },
  { cat: 'Vận hành', kw: 'transshipment trung chuyen chuyen tai la gi', a: 'Transshipment (trung chuyển): container được dỡ từ tàu này và xếp lên tàu khác tại cảng để đi tiếp, không vào nội địa. Cảng trung chuyển lớn cần xếp bãi & lịch tàu rất tối ưu.' },
  { cat: 'Vận hành', kw: 'reefer hang lanh container lanh o cam dien', a: 'Reefer là container lạnh có máy làm lạnh, cần ổ cắm điện (reefer plug) tại bãi và giám sát nhiệt độ liên tục (vd -18°C). Bãi reefer trong twin hiển thị số ổ cắm & % đang dùng.' },
  { cat: 'Vận hành', kw: 'hang nguy hiem dg imdg nguy hiem class', a: 'Hàng nguy hiểm (DG/IMDG) phân theo Class (3 chất lỏng cháy, 8 ăn mòn, 2 khí nén, 9 khác…), phải lưu khu riêng, giữ khoảng cách an toàn ≥3m và quy trình kiểm soát chặt.' },
  { cat: 'Vận hành', kw: 'oog hang qua kho qua tai flat rack open top', a: 'OOG (Out Of Gauge) là hàng quá khổ/quá tải, dùng container Flat Rack/Open Top, cần không gian & thiết bị đặc biệt (một kiện OOG có thể chiếm chỗ ~6 container thường).' },
  { cat: 'Vận hành', kw: 'mon nuoc draft do sau luong lach', a: 'Mớn nước (draft) là độ chìm của tàu; luồng lạch phải đủ sâu cho mớn nước tàu lớn. Twin theo dõi mớn nước & thủy triều để điều phối cập bến an toàn.' },
  { cat: 'Vận hành', kw: 'hoa tieu pilot tau lai dat tugboat lai dat', a: 'Hoa tiêu (pilot) lên tàu dẫn vào luồng; tàu lai dắt (tugboat) hỗ trợ cập/rời bến an toàn. Đây là khâu bắt buộc với tàu lớn trong vùng nước cảng.' },
  { cat: 'Vận hành', kw: 'lich tau vessel schedule eta etd khi nao tau den', a: 'Lịch tàu (ETA/ETD = giờ dự kiến đến/đi) lấy từ AIS + hãng tàu. Điều phối JIT dùng ETA chính xác (±10 phút) để tàu đến đúng lúc bến trống. Hỏi "tàu [tên] đang làm gì" để xem trạng thái.' },
  { cat: 'Vận hành', kw: 'hai quan customs thong quan giay to thu tuc', a: 'Thông quan hải quan: khai báo điện tử, đối chiếu chứng từ (vận đơn, manifest), kiểm tra/soi chiếu nếu cần. Cổng số hóa giúp xác thực lệnh điện tử tự động, giảm hồ sơ giấy về 0.' },
  { cat: 'Vận hành', kw: 'van don bill of lading b/l chung tu', a: 'Vận đơn (Bill of Lading) là chứng từ vận tải xác nhận hàng đã nhận để chở, là cơ sở giao nhận & sở hữu hàng. Hệ thống cảng đối chiếu B/L với lệnh giao nhận điện tử.' },
  { cat: 'Vận hành', kw: 'so hieu container number iso 6346 dinh dang', a: 'Số container theo chuẩn ISO 6346: 4 chữ (3 chủ sở hữu + U) + 6 số + 1 số kiểm tra, ví dụ MSCU 123456-7. Bấm vào xe/bãi để xem số container thực tế.' },

  /* ── KHÁCH HÀNG / THƯƠNG MẠI (mô hình demo) ───────────────────────────── */
  { cat: 'Khách hàng', kw: 'dat cho booking dat lich xe tai slot vao cang the nao', a: 'Trong mô hình NDT15, xe tải đặt "Booking Slot" qua app trước (vd 24 giờ), nhận mã QR chứa container ID + giờ + cổng + tuyến trong cảng. Đến giờ, camera ALPR quét biển số và mở barrier tự động.', act: { feature: 'CỔNG' } },
  { cat: 'Khách hàng', kw: 'tra cuu theo doi container o dau status tracking', a: 'Bạn có thể theo dõi container theo thời gian thực trong twin: hỏi tôi "container [số] ở đâu" hoặc bấm vào bãi/xe để xem vị trí, trạng thái, ETA. (Trong vận hành thật, tra cứu qua portal cảng/hãng tàu.)' },
  { cat: 'Khách hàng', kw: 'gio lam viec mo cua hoat dong 24/7 khi nao', a: 'Cảng thông minh NDT15 vận hành 24/7 — cổng tự động, bến tự động (AGV/ASC) và an ninh drone chạy liên tục cả ngày lẫn đêm (bật chế độ 🌙 Night để xem hoạt động ban đêm).' },
  { cat: 'Khách hàng', kw: 'lien he contact ho tro cskh so dien thoai email', a: 'Đây là bản sao số trình diễn (digital twin demo) của Cảng NDT15. Thông tin liên hệ/hỗ trợ khách hàng sẽ theo kênh chính thức của đơn vị vận hành; trong twin, bạn cứ hỏi tôi mọi thứ về cảng.' },
  { cat: 'Khách hàng', kw: 'bieu phi charges fee gia dich vu chi phi bao nhieu', a: 'Biểu phí (xếp dỡ, lưu bãi, điện reefer, cân tải…) do đơn vị khai thác công bố theo từng dịch vụ. Điểm mạnh của cảng số: minh bạch hóa và liên kết hoạt động vật lý với dòng tiền (tính năng Tài chính & Năng lượng).', act: { feature: 'NĂNG LƯỢNG' } },
  { cat: 'Khách hàng', kw: 'freight forwarder dai ly giao nhan logistics dat tau', a: 'Freight forwarder (đại lý giao nhận) lo việc đặt chỗ với hãng tàu, vận tải drayage, khai báo xuất nhập và làm trung gian với các nhà vận chuyển — đầu mối logistics cho chủ hàng.' },
  { cat: 'Khách hàng', kw: 'tra vo container rong empty return doi vo', a: 'Trả/đổi vỏ container rỗng: xe tải đặt slot, vào cổng, RTG/RMG giao nhận vỏ tại bãi rỗng. Twin theo dõi tồn vỏ để cân đối, giảm đảo chuyển vô ích.' },
  { cat: 'Khách hàng', kw: 'vgm can tai trong luong weighing khoi luong', a: 'VGM (Verified Gross Mass) là khối lượng toàn bộ đã kiểm chứng của container, bắt buộc khai trước khi xếp lên tàu (SOLAS). Trạm cân tải (kể cả cân ngầm) đo và đẩy số liệu về hệ thống.' },
  { cat: 'Khách hàng', kw: 'chung tu giay to can gi ho so xuat nhap', a: 'Hồ sơ thường gồm: booking, vận đơn (B/L), packing list, invoice, tờ khai hải quan, VGM. Cảng số hóa hướng tới chứng từ điện tử, lệnh giao nhận điện tử (eDO), giảm giấy tờ.' },

  /* ── CÔNG NGHỆ ─────────────────────────────────────────────────────────── */
  { cat: 'Công nghệ', kw: 'bim mo hinh thong tin cong trinh la gi', a: 'BIM (Building Information Modeling): mô hình số 3D giàu thông tin của công trình/hạ tầng. Twin dùng BIM dựng bãi, cẩu, công trình 1:1 và gắn dữ liệu vận hành.' },
  { cat: 'Công nghệ', kw: 'gis ban do khong gian dia ly he thong', a: 'GIS (Geographic Information System): hệ bản đồ không gian địa lý — luồng lạch, vùng neo, bố trí bãi/đường — nền tảng định vị mọi đối tượng trong twin.' },
  { cat: 'Công nghệ', kw: '5g mang khong day toc do cao ket noi', a: '5G cung cấp kết nối băng rộng độ trễ thấp cho AGV, drone, camera và cảm biến dày đặc — xương sống truyền dữ liệu real-time của cảng tự động.' },
  { cat: 'Công nghệ', kw: 'blockchain chuoi khoi truy xuat chung tu', a: 'Blockchain dùng cho chứng từ & truy xuất nguồn gốc chống sửa (eB/L, lệnh giao nhận, hộ chiếu carbon container) — tăng minh bạch và tin cậy giữa các bên.' },
  { cat: 'Công nghệ', kw: 'an ninh mang cybersecurity bao ve he thong tan cong', a: 'An ninh mạng cảng: phân vùng mạng (IT/OT), mã hóa, giám sát bất thường, kế hoạch ứng phó. Twin mô phỏng được tấn công mạng vào cổng để diễn tập (kịch bản GATE_CYBER).' },
  { cat: 'Công nghệ', kw: 'tos terminal operating system he thong khai thac', a: 'TOS (Terminal Operating System) là hệ điều hành khai thác cảng: quản lý tàu, bãi, lệnh cẩu, cổng. Twin đồng bộ với TOS để phản ánh và tối ưu khai thác.' },
  { cat: 'Công nghệ', kw: 'api tich hop ket noi he thong khac integration', a: 'Twin tích hợp qua API với TOS, hải quan, hãng tàu, đường sắt và lưới điện — để dữ liệu chảy thông suốt giữa các hệ thống thay vì ốc đảo.' },
  { cat: 'Công nghệ', kw: 'phan tich du lieu analytics dashboard bao cao', a: 'Phân tích dữ liệu biến số liệu thô thành chỉ số (KPI), bảng nhiệt, dashboard và cảnh báo — vd điểm ESG, công suất bãi, JIT, chi phí điện. Mở một tính năng để xem biểu đồ.' },

  /* ── MÔI TRƯỜNG / ESG ─────────────────────────────────────────────────── */
  { cat: 'Môi trường', kw: 'dien bo shore power onshore power cold ironing', a: 'Điện bờ (shore power/cold ironing) cho tàu cắm điện khi cập bến để tắt máy phát dầu → giảm ~90% CO₂ và tiếng ồn tại bến. NDT15 có trạm điện bờ kích hoạt khi tàu cập.', act: { feature: 'MÔI TRƯỜNG' } },
  { cat: 'Môi trường', kw: 'khi thai co2 sox nox phat thai do dac', a: 'Cảm biến IoT đo CO₂, SOx, NOx tại điểm chiến lược dọc bến (1 phút/lần) để tính chỉ số phát thải, đối chiếu chuẩn IMO và cảnh báo khi vượt ngưỡng.', act: { feature: 'MÔI TRƯỜNG' } },
  { cat: 'Môi trường', kw: 'trung hoa carbon net zero giam phat thai muc tieu', a: 'Hướng net-zero/giảm carbon: điện bờ, năng lượng tái tạo (gió/mặt trời), hydro xanh, thiết bị điện (e-RTG/e-truck) và tối ưu vận hành để cắt phát thải. Twin đo & báo cáo tiến độ.' },
  { cat: 'Môi trường', kw: 'imo 2020 2050 tieu chuan hang hai luu huynh', a: 'IMO đặt chuẩn phát thải hàng hải: IMO 2020 giới hạn lưu huỳnh nhiên liệu 0.5%, và lộ trình giảm khí nhà kính tới 2050. Báo cáo ESG của cảng đối chiếu các chuẩn này.' },
  { cat: 'Môi trường', kw: 'cang xanh green port la gi tieu chi', a: 'Cảng xanh: vận hành giảm phát thải & tác động môi trường — điện bờ, năng lượng tái tạo, quan trắc nước/không khí, quản lý chất thải, và minh bạch ESG. NDT15 mô phỏng đầy đủ qua lớp EIS.', act: { feature: 'MÔI TRƯỜNG' } },
  { cat: 'Môi trường', kw: 'chat luong nuoc bien wqi quan trac do duc ph', a: 'Quan trắc nước biển: phao cảm biến đo WQI, độ đục, pH, hydrocarbon real-time để phát hiện ô nhiễm/tràn dầu sớm và phục vụ kiểm toán ESG.' },
  { cat: 'Môi trường', kw: 'bao cao esg report kiem toan xuat bao cao', a: 'Dashboard ESG tổng hợp phát thải, năng lượng, nước; xuất báo cáo chuẩn (IMO/khung ESG) 1-click cho kiểm toán độc lập và để hãng tàu ưu tiên chọn cảng.', act: { feature: 'MÔI TRƯỜNG' } },
  { cat: 'Môi trường', kw: 'thue carbon eu ets carbon tax chi phi', a: 'Thuế/giá carbon (EU ETS, cơ chế carbon) tạo áp lực chi phí lên phát thải. Cảng đo phát thải chính xác để quản trị chi phí carbon và chứng minh tuân thủ.' },
  { cat: 'Môi trường', kw: 'tieng on noise o nhiem am khu dan cu', a: 'Tiếng ồn cảng (cẩu, xe, tàu) được giám sát; điện bờ và thiết bị điện giúp giảm ồn ban đêm, hạn chế ảnh hưởng khu dân cư lân cận.' },

  /* ── NĂNG LƯỢNG ───────────────────────────────────────────────────────── */
  { cat: 'Năng lượng', kw: 'microgrid luoi dien sieu nho tu chu nang luong', a: 'Microgrid: lưới điện cục bộ kết hợp điện gió + mặt trời + pin lưu trữ (BESS) + lưới, tự cân đối để cấp điện ổn định cho cảng và giảm phụ thuộc lưới quốc gia.' },
  { cat: 'Năng lượng', kw: 'bess pin luu tru battery storage', a: 'BESS (Battery Energy Storage System): hệ pin lưu trữ điện tái tạo dư để dùng lúc cao điểm/mất lưới, ổn định microgrid và cắt đỉnh chi phí điện.', act: { fly: 'energy' } },
  { cat: 'Năng lượng', kw: 'hydro xanh hydrogen nhien lieu sach bunkering', a: 'Hydro xanh sản xuất bằng điện tái tạo (điện phân nước), lưu trữ và tiếp nhiên liệu (bunkering) cho tàu/thiết bị — hướng khử carbon dài hạn. Xem Green Energy Hub.', act: { fly: 'energy' } },
  { cat: 'Năng lượng', kw: 'e-rtg e-truck thiet bi dien dien khi hoa', a: 'Điện khí hóa thiết bị: e-RTG, e-truck, AGV chạy điện thay dầu → giảm phát thải & chi phí nhiên liệu, nạp điện từ microgrid/trạm sạc của Green Hub.' },
  { cat: 'Năng lượng', kw: 'du bao gia dien toi uu chi phi hoa don dien', a: 'Twin dự báo giá điện & nhu cầu, dịch tải sang giờ thấp điểm và ưu tiên nguồn tái tạo → tối ưu hóa đơn điện (mục tiêu -15%).', act: { feature: 'NĂNG LƯỢNG' } },

  /* ── AN NINH / AN TOÀN ────────────────────────────────────────────────── */
  { cat: 'An ninh', kw: 'isps code an ninh hang hai tieu chuan', a: 'Bộ luật ISPS (An ninh tàu & bến cảng) quy định kiểm soát ra vào, nhận diện, và kế hoạch an ninh. Lớp SSIS của twin số hóa giám sát theo tinh thần ISPS.' },
  { cat: 'An ninh', kw: 'kiem soat ra vao access control the cong nhan dien', a: 'Kiểm soát ra vào: ALPR cho xe, thẻ/sinh trắc cho người, đối chiếu lệnh điện tử; mọi lượt ghi audit log. Khu hạn chế giám sát bằng camera + radar.' },
  { cat: 'An ninh', kw: 'camera cctv giam sat hinh anh nhiet', a: 'Hệ camera (gồm camera nhiệt trên drone) giám sát 24/7; AI phân tích video phát hiện xâm nhập/bất thường và cảnh báo về trung tâm.' },
  { cat: 'An ninh', kw: 'phong chay chua chay fire safety chay no', a: 'An toàn cháy nổ: cảm biến khói/nhiệt, bồn nước & nhiên liệu dự trữ ngầm, quy trình sơ tán. Twin mô phỏng được kịch bản cháy để diễn tập ứng phó.' },
  { cat: 'An ninh', kw: 'ung pho su co emergency response khan cap', a: 'Ứng phó sự cố: twin phát hiện → cảnh báo trung tâm → điều lực lượng/drone → ghi nhận. Có thể diễn tập trước bằng mô phỏng (cháy, tràn dầu, xâm nhập, cyber).', act: { picker: true } },

  /* ── CHỐNG CHỊU / KHÍ HẬU ─────────────────────────────────────────────── */
  { cat: 'Chống chịu', kw: 'nuoc bien dang sea level rise bien doi khi hau', a: 'Nước biển dâng đe dọa cảng ven biển. Twin mô phỏng kịch bản dâng (vd +2.4m) để xem hạ tầng nào ngập (kể cả trạm điện ngầm) và lên kế hoạch nâng cao trình/bơm thoát.', act: { picker: true } },
  { cat: 'Chống chịu', kw: 'bao storm surge trieu cuong ngap lut ung pho', a: 'Bão & triều cường: twin mô phỏng gió mạnh (cẩu ngừng, drone hạ cánh) + nước dâng + ngập hạ tầng, và lộ trình phục hồi (bơm thoát nước, chuyển nguồn). Chạy kịch bản "Bão + nước dâng".', act: { fork: 'STORM_SURGE' } },
  { cat: 'Chống chịu', kw: 'business continuity duy tri van hanh phuc hoi tham hoa', a: 'Khả năng chống chịu: twin giúp dự phòng (nguồn điện, lộ trình thay thế), mô phỏng sự cố trước, và ước tính thời gian phục hồi — giảm gián đoạn khai thác.' },
  { cat: 'Chống chịu', kw: 'tram bom chong ngap thoat nuoc thuy van mua', a: 'Trạm bơm thoát nước ngầm thu & bơm nước mưa/triều cường ra biển, chống ngập mặt bằng cảng. Twin mô phỏng ngập theo kịch bản mưa/bão để vận hành bơm chủ động.', act: { descend: true } },

  /* ── TỰ ĐỘNG HÓA / TƯƠNG LAI ──────────────────────────────────────────── */
  { cat: 'Tự động hóa', kw: 'asc cau xep tu dong automated stacking crane', a: 'ASC (Automated Stacking Crane): cẩu xếp chồng tự động làm việc trong bãi không người lái, phối hợp với AGV — lõi của bến tự động.', act: { fly: 'auto' } },
  { cat: 'Tự động hóa', kw: 'xe tai tu lai autonomous truck khong nguoi lai', a: 'Xe tải/AGV tự lái dùng LiDAR + định vị chính xác chạy theo tuyến cố định trong cảng, an toàn và 24/7 — giảm phụ thuộc tài xế và tăng độ ổn định.', act: { fly: 'auto' } },
  { cat: 'Tự động hóa', kw: 'loi ich tu dong hoa automation vi sao', a: 'Lợi ích tự động hóa: vận hành 24/7 ổn định, năng suất cao, an toàn hơn, giảm chi phí nhân công lặp lại và giảm phát thải (thiết bị điện). Xem bến tự động.', act: { feature: 'TỔNG QUAN' } },
  { cat: 'Tự động hóa', kw: 'cang tuong lai 2040 next gen smart port', a: 'Cảng tương lai: tự động hóa toàn diện, năng lượng xanh/hydro, AI điều phối, đa phương thức (tàu–ray–đường bộ–ngầm) và digital twin cấp prescriptive. NDT15 mô phỏng tầm nhìn đó.' },
  { cat: 'Tự động hóa', kw: 'da phuong thuc multimodal ket noi ray duong bo', a: 'Đa phương thức (multimodal): kết nối tàu biển ↔ đường sắt ↔ đường bộ ↔ tuyến hầm ngầm để luân chuyển container tối ưu, giảm xe tải đường bộ và phát thải.' },

  /* ── CHRONOS / ỨNG DỤNG ───────────────────────────────────────────────── */
  { cat: 'CHRONOS', kw: 'cach tua lai qua khu replay xem lai dieu khien thoi gian', a: 'Dùng thanh CHRONOS dưới màn hình: ◀◀ tua ngược (bấm lại để ×2/×4/×8), ❚❚ dừng, ▶▶ tua tới, ⦿ Thực Tại về hiện tại, ⏮/⏭ tới mốc sớm/muộn nhất. Hoặc bảo tôi "tua lại".' },
  { cat: 'CHRONOS', kw: 'xem tuong lai du bao precognition keo phai', a: 'Kéo con trỏ thời gian sang phải (vùng TƯƠNG LAI) hoặc bấm ⏭ để xem lớp "bóng ma" cyan — vị trí tàu dự báo sắp tới. Hoặc bảo tôi "cho xem tương lai".', act: { future: 90 } },
  { cat: 'CHRONOS', kw: 'danh sach kich ban su co fork co nhung gi', a: 'Các kịch bản mô phỏng: 🛠 Cẩu B-03 hỏng · 🚢 Dồn 3 tàu · 🌊 Bão + nước dâng · 🛡 Tấn công mạng cổng · ⚡ Mất điện lưới. Bấm "⚡ Fork Reality" để chọn, hoặc nói "nếu … thì sao".', act: { picker: true } },
  { cat: 'CHRONOS', kw: 'ai hoa giai mitigation giam thiet hai cuu', a: 'Khi đang mô phỏng sự cố, bấm "🤖 AI Hóa Giải" (hoặc nói "hóa giải") để áp phương án đối ứng — đường phản thực sẽ uốn lại gần baseline, chứng minh giá trị quyết định.' },

  /* ── SO SÁNH / CHIẾN LƯỢC ─────────────────────────────────────────────── */
  { cat: 'Chiến lược', kw: 'so sanh singapore rotterdam cang khac the gioi', a: 'Các cảng lớn (Singapore Tuas, Rotterdam, Antwerp) mạnh về tự động hóa & digital twin "phản chiếu". Điểm khác của NDT15: cỗ máy thời gian CHRONOS (tua/fork/tương lai) + tầng hạ tầng ngầm + trợ lý hội thoại — twin tương tác trên web ai cũng mở được.' },
  { cat: 'Chiến lược', kw: 'vi sao chon ndt15 doc dao loi the canh tranh dau tu', a: 'Lợi thế NDT15: không chỉ giám sát mà còn TUA THỜI GIAN, MÔ PHỎNG SỰ CỐ và TỰ GIẢI THÍCH (Glass Box) — đạt cấp prescriptive; chạy trực tiếp trên web, dễ trình diễn cho nhà đầu tư & ra quyết định nhanh.' },
  { cat: 'Chiến lược', kw: 'gia tri cho nha dau tu lanh dao chinh phu', a: 'Với lãnh đạo/nhà đầu tư: twin trực quan hóa rủi ro & cơ hội (bão, mất điện, tắc nghẽn), định lượng tác động bằng tiền/CO₂, và thử phương án trước khi rót vốn — giảm rủi ro quyết định hạ tầng lớn.' },
  { cat: 'Chiến lược', kw: 'mo rong nang cap tuong lai lo trinh phat trien', a: 'Lộ trình mở rộng: thêm cảm biến/độ phủ dữ liệu, nâng AI lên prescriptive/autonomous, tích hợp hành lang số liên cảng, và mở rộng kịch bản chống chịu khí hậu. Kiến trúc twin cho phép cắm thêm lớp dễ dàng.' },
];
